version: "3.7"

services:
  webclient:
    container_name: webclient
    image: webconcierge-client
    build:
      context: ./webclient
      dockerfile: Dockerfile
    volumes:
      - "./webclient:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  server:
    container_name: server
    image: webconcierge-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
